### ISSUE TITLE
Applicants not clear why passport number is being asked for twice during online verification process

### ISSUE THREAD

**Issue by wnialloconnor** [alphagov/employee-id#16]
**Where?**
https://work-in-gov.herokuapp.com/v2/pre-interview/3rd-cycle-matching

**1) 
Add the question “Do you have a UK passport?”**  
**If yes -** then the box appears to input number and the explanatory text below it.
**If no -** then should allow candidate to progress to next page

**2) 
Remove the** “I don’t have a UK passport link”

**3)
Move text:**
Above text input.

**Change from:**
If you have a UK passport, we'll take a photo of you at your interview and automatically check it against your passport photo.

**Change to:**
By entering your passport details below, you are giving permission to access your details with her Majesty’s Passport Office (HM Passport Office). We will take a photo of you on the day of your interview and compare it with these details to confirm your identity.

The photo will not be stored and will be deleted as soon as the comparison is completed.

**Comment by suryanaga** [comment]
@wnialloconnor Is this still an issue?
