### ISSUE TITLE
ID Checkers want the ability to preview the Verify and ID Checking Journey

### ISSUE THREAD

**Issue by wnialloconnor** [alphagov/employee-id#40]
**Where?**
Guidance Screen

**Why?**
ID Checkers want the ability to preview the applicants verify journey so they understand the process in case an applicant encounters any difficult. This will also help them understand the process.

ID Checkers also want the ability to preview and test the ID Checking Process before using it for the first time.

**Comment by suryanaga** [comment]
3 options for this could be:

 - Screenshots
 - Fake code to step through journey (maybe add test banner?)
 - Video
